services:
  redis:
    image: redis:7.4.0-alpine3.20
    container_name: my-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

  local:
    build:
      context: ./docker/local
      args:
        LOCAL_DEVELOPMENT_SSH_PASSWORD: ${LOCAL_DEVELOPMENT_SSH_PASSWORD:?Missing LOCAL_DEVELOPMENT_SSH_PASSWORD}
        LOCAL_DEVELOPMENT_UID: ${LOCAL_DEVELOPMENT_UID:-1000}
    ports:
      - ${LOCAL_DEVELOPMENT_SSH_PORT:?Missing LOCAL_DEVELOPMENT_SSH_PORT}:22
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - home:/home/ubuntu
      - ./:/workspace/granadinha

volumes:
  redis_data:
  home:
